services:
  bot:
    build: .
    container_name: al-bot
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./credentials.json:/app/credentials.json:rw
    environment:
      - NODE_ENV=production

networks:
  default:
    name: al-network
